apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "xanthus-platform.configMapName" . }}
  labels:
    {{- include "xanthus-platform.labels" . | nindent 4 }}
data:
  {{- with .Values.configMap.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}