apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xanthus-platform.secretName" . }}
  labels:
    {{- include "xanthus-platform.labels" . | nindent 4 }}
type: Opaque
data:
  {{- with .Values.secret.data }}
  {{- toYaml . | nindent 2 }}
  {{- end }}