apiVersion: v1
kind: Secret
metadata:
  name: {{ include "xanthus-code-server.fullname" . }}
  labels:
    {{- include "xanthus-code-server.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install
type: Opaque
data:
  {{- if .Values.password }}
  password: {{ .Values.password | b64enc | quote }}
  {{- else }}
  password: {{ randAlphaNum 32 | b64enc | quote }}
  {{- end }}