## Default values for xanthus-platform
## This is a YAML-formatted file.

## Image configuration
image:
  repository: ghcr.io/chrishham/xanthus
  pullPolicy: IfNotPresent
  tag: "latest"

## Image pull secrets
imagePullSecrets: []

## Service account
serviceAccount:
  create: true
  annotations: {}
  name: ""

## Pod annotations
podAnnotations: {}

## Pod security context
podSecurityContext:
  fsGroup: 1000

## Container security context
securityContext:
  allowPrivilegeEscalation: false
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

## Service configuration
service:
  type: ClusterIP
  port: 8081

## Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: xanthus.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

## Resource limits
resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

## Horizontal Pod Autoscaler
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

## Node selector
nodeSelector: {}

## Tolerations
tolerations: []

## Affinity
affinity: {}

## Persistence configuration
persistence:
  enabled: true
  storageClass: ""
  accessMode: ReadWriteOnce
  size: 10Gi
  annotations: {}

## Environment variables
env:
  - name: GIN_MODE
    value: "release"
  - name: PORT
    value: "8081"
  - name: DATA_DIR
    value: "/app/data"

## Config map data
configMap:
  data: {}

## Secret data
secret:
  data: {}

## Readiness probe
readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10

## Liveness probe
livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 30
  periodSeconds: 30

## Startup probe
startupProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 10
  failureThreshold: 30

## Pod disruption budget
podDisruptionBudget:
  enabled: false
  minAvailable: 1

## Network policy
networkPolicy:
  enabled: false
  ingress: []
  egress: []